# Generated by Django 3.0.6 on 2020-06-23 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20200624_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DSL',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='DSL Number must be entered exactly 10 digits.', regex='^(\\d{10})$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='DSL',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='DSL Number must be entered exactly 10 digits.', regex='^(\\d{10})$')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='Mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')]),
        ),
    ]
