# Generated by Django 3.0.6 on 2020-06-23 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20200624_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='tower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tower_flat', to='emp.Tower'),
            preserve_default=False,
        ),
    ]
