# Generated by Django 3.0.6 on 2020-06-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='Avatar',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='store',
            name='Type',
            field=models.CharField(choices=[('shop', 'Shop'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('gym', 'Gym')], default='shop', max_length=12),
        ),
    ]
