# Generated by Django 3.0.6 on 2020-06-24 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20200624_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='Mobile',
            field=models.CharField(default=1, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='Relationship',
            field=models.CharField(choices=[('wife', 'Wife'), ('son', 'Son'), ('daughter', 'Daughter'), ('cousin', 'Cousin'), ('husband', 'Husband')], default='wife', max_length=9),
        ),
    ]
