# Generated by Django 3.0.6 on 2020-06-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0009_auto_20200625_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='Address',
        ),
        migrations.AddField(
            model_name='owner',
            name='Code',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptower',
            name='Paid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptower',
            name='Total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptower',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emp.Admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptower',
            name='proofTransaction',
            field=models.FileField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownershiptower',
            name='serialTransaction',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
