# Generated by Django 3.0.6 on 2020-06-28 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_auto_20200625_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='NID',
        ),
        migrations.AddField(
            model_name='requests',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Mobile Number must be entered exactly 11 digits.', regex='^(\\d{11})$')]),
        ),
    ]
