# Generated by Django 3.0.6 on 2020-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_auto_20200628_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Type',
            field=models.CharField(choices=[('طلب', 'طلب'), ('شكوي', 'شكوي')], default='طلب', max_length=9),
        ),
    ]
