# Generated by Django 3.0.6 on 2020-07-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0016_requests_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Avatar',
            field=models.FileField(upload_to='images'),
        ),
    ]
