# Generated by Django 3.0.6 on 2020-07-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0017_auto_20200706_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
