# Generated by Django 3.0.6 on 2020-07-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0018_auto_20200706_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='Avatar',
        ),
    ]
