# Generated by Django 3.0.6 on 2020-07-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0020_auto_20200712_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='Type',
            field=models.CharField(choices=[('shop', 'Shop'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('gym', 'Gym'), ('mall', 'Mall')], default='shop', max_length=12),
        ),
    ]
